services:
  todo-app:
    build: .
    ports:
      - "3001:5000"
    volumes:
      - ./data:/app/server/data
    environment:
      - NODE_ENV=production
    restart: unless-stopped

volumes:
  data: 